Traceback (most recent call last):
  File "/var/opt/condor/execute/dir_1635611/condor_exec.exe", line 175, in <module>
    main(sys.argv[1:])
  File "/var/opt/condor/execute/dir_1635611/condor_exec.exe", line 171, in main
    performPlacement(inputfile,outputfile)
  File "/var/opt/condor/execute/dir_1635611/condor_exec.exe", line 90, in performPlacement
    pMover.client(host,port)
  File "/var/opt/condor/execute/dir_1635611/IrodsMover.py", line 59, in client
    self.run()
  File "/var/opt/condor/execute/dir_1635611/DataMover.py", line 143, in run
    errhandler=self.stderrHandler)
  File "/var/opt/condor/execute/dir_1635611/TimedExec.py", line 100, in runTimedCmd
    stderr=errtype, stdout=outtype)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
